#!/bin/bash

# builds the JCL needed to install DSCOPY

cat << 'END'
//DSCOPY JOB (JOB),
//             'INSTALL DSCOPY',
//             CLASS=A,
//             MSGCLASS=A,
//             MSGLEVEL=(1,1),
//             USER=IBMUSER,
//             PASSWORD=SYS1
END

cat << 'END'
//PROC   EXEC PGM=PDSLOAD
//STEPLIB  DD  DSN=SYSC.LINKLIB,DISP=SHR
//SYSPRINT DD  SYSOUT=*
//SYSUT2   DD  DSN=SYS1.CMDPROC,DISP=SHR
//SYSUT1   DD  DATA,DLM=@@
./ ADD NAME=CDSCPY0
END
cat V0R9M00.CLIST.TAPE/CDSCPY0.txt
echo "@@"

cat << 'END'
//HELP   EXEC PGM=PDSLOAD
//STEPLIB  DD  DSN=SYSC.LINKLIB,DISP=SHR
//SYSPRINT DD  SYSOUT=*
//SYSUT2   DD  DSN=SYS2.HELP,DISP=SHR
//SYSUT1   DD  DATA,DLM=@@
./ ADD NAME=CDSCPY0
END
cat V0R9M00.HELP.TAPE/CDSCPY0.txt
echo "@@"


cat << 'END'
//PLIB   EXEC PGM=PDSLOAD
//STEPLIB  DD  DSN=SYSC.LINKLIB,DISP=SHR
//SYSPRINT DD  SYSOUT=*
//SYSUT2   DD  DSN=SYSGEN.ISPF.PLIB,DISP=SHR
//SYSUT1   DD  DATA,DLM=@@
./ ADD NAME=HDCPY0
END
cat V0R9M00.ISPF.TAPE/HDCPY0.txt
echo "./ ADD NAME=HDCPY0R"
cat V0R9M00.ISPF.TAPE/HDCPY0R.txt
echo "./ ADD NAME=PDCPY0"
cat V0R9M00.ISPF.TAPE/PDCPY0.txt
echo "./ ADD NAME=PDCPY0R"
cat V0R9M00.ISPF.TAPE/PDCPY0R.txt
echo "./ ADD NAME=PDCPY1"
cat V0R9M00.ISPF.TAPE/PDCPY1.txt
echo "@@"

cat << 'END'
//MLIB   EXEC PGM=PDSLOAD
//STEPLIB  DD  DSN=SYSC.LINKLIB,DISP=SHR
//SYSPRINT DD  SYSOUT=*
//SYSUT2   DD  DSN=SYSGEN.ISPF.MLIB,DISP=SHR
//SYSUT1   DD  DATA,DLM=@@
./ ADD NAME=DCPY00
END
cat V0R9M00.ISPF.TAPE/DCPY00.txt
echo "./ ADD NAME=DCPY01"
cat V0R9M00.ISPF.TAPE/DCPY01.txt
echo "./ ADD NAME=DCPY02"
cat V0R9M00.ISPF.TAPE/DCPY02.txt
echo "@@"
